### ISSUE TITLE
Create Special Collections Page for Africans in America

### ISSUE THREAD

**Issue by Muraszko-wgbh** [WGBH-MLA/openvault3#687]
- [ ] Create collection page in markdown
- [ ] Fix method validation errors for ingest:
_Method validation errors: '#special_collections_hash' failed: 'africans-america' is not a valid path under '/var/www/openvault/releases/20170309133018/app/views/collections'; Expected one of ["advocates", "american-archive-of-public-broadcasting", "boston-tv-news", "from_the_vault", "march_on_washington", "new_television_workshop", "press_people", "rock_roll", "say_brother", "stock-sales", "vietnam", "war_peace"]_
- [ ] Re-ingest xml and swap server

**Comment by Muraszko-wgbh** [comment]
Waiting on Legal to approve interviews and waiting on text and image for collection page

**Comment by sroosa** [comment]
release a long  time ago
