### ISSUE TITLE
Update record in OpenVault and re-indeix public site

### ISSUE THREAD

**Issue by singlesoliloquy** [WGBH-MLA/openvault3#737]
From Casey:

If anyone has 15 min to spare sometime this week, it would be great to get it taken care of, as one of our scholars is getting an article published about her exhibit. I need this annotation:
<pbcoreAnnotation annotationType="Scholar Exhibit">zoom</pbcoreAnnotation>
Added to this record: http://openvault.wgbh.org/catalog/V_B5912EDBF6C04D0DB1AF47ABE7D9536A
And then have the record reindexed on the public site. I don't think any changes are needed in the Exhibit Markdown file.

Done when: annotation has been added to record and site re-indexed.

**Comment by foo4thought** [comment]
I restored Casey's access to the FileMaker database used to control our custom metadata, added the custom tag, exported to file, uploaded the file to openvault host, ran the ingest script but Casey says another step is needed to update the exhibit data?

**Comment by singlesoliloquy** [comment]
Kevin did this.
