### ISSUE TITLE
Wagtail API Configuration

### ISSUE THREAD

**Issue by jasoncorum** [WGBH-MLA/openvault3#759]
After completing #758, configure the local Wagtail application to have an API to explore using it as a headless CMS. https://docs.wagtail.io/en/stable/advanced_topics/api/v2/configuration.html

**Done When**
- [x] We have an API we can evaluate for using Wagtail as a headless CMS
- [x] We document its use against our user stories here: https://docs.google.com/spreadsheets/d/1ziBD2455glo9_aH7wvEfB0pKcmwgtUTDTBxl3rf2PE4/edit#gid=0

**Comment by afred** [comment]
Done. See progress on test app here: https://github.com/WGBH-MLA/ov_wag
